version: '3'
name: "idnes"
services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.0
    container_name: elasticsearch1
    environment:
      - "discovery.type=single-node"
    volumes:
      - elastic_data:/usr/share/elasticsearch/data:rw
    ports:
      - 9200:9200
    networks:
      - elk
    deploy:
      resources:
        limits:
          memory: 2G
    restart: unless-stopped
  kibana:
    depends_on:
    - elastic
    image: docker.elastic.co/kibana/kibana:8.7.0
    networks:
      - elk
    ports:
      - 5601:5601
    restart: unless-stopped
volumes:
  elastic_data:
    driver: local
networks:
  elk: